# Generated by Django 4.1.5 on 2023-03-10 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_remove_employee_ccontact_remove_employee_cemail_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='uploads',
        ),
        migrations.AddField(
            model_name='employee',
            name='uploads1',
            field=models.FileField(null=True, upload_to='uploads/'),
        ),
    ]
