# Generated by Django 4.1.5 on 2023-03-10 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_remove_employee_uploads_employee_uploads1'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employee',
            new_name='Uploadedfiles',
        ),
    ]
